export const SUPPORTED_DOMAINS = [
  'aasanetidende.no',
  'aasavis.no',
  'akersposten.no',
  'amta.no',
  'an.no',
  'ao.no',
  'auraavis.no',
  'austagderblad.no',
  'avisa-hordaland.no',
  'avisagaula.no',
  'avisenagder.no',
  'ba.no',
  'bodonu.no',
  'bondebladet.no',
  'budstikka.no',
  'bygdebladet.no',
  'bygdeposten.no',
  'dagbladet.no',
  'dalane-tidende.no',
  'dn.no',
  'drangedalsposten.no',
  'dt.no',
  'e24.no',
  'eikerbladet.no',
  'enebakkavis.no',
  'f-b.no',
  'fanaposten.no',
  'finnmarksposten.no',
  'firda.no',
  'firdaposten.no',
  'fremover.no',
  'gbnett.no',
  'gjengangeren.no',
  'glomdalen.no',
  'h-a.no',
  'h-avis.no',
  'ha-halden.no',
  'hadeland.no',
  'hammerfestingen.no',
  'hardanger-folkeblad.no',
  'helg.no',
  'ifinnmark.no',
  'iharstad.no',
  'indre.no',
  'isandnessjoen.no',
  'jarlsbergavis.no',
  'jbl.no',
  'karmoynytt.no',
  'kronstadposten.no',
  'krs.no',
  'kv.no',
  'kvinnheringen.no',
  'laagendalsposten.no',
  'lierposten.no',
  'lofot-tidende.no',
  'lofotposten.no',
  'lokal-avisa.no',
  'lyngdalsavis.no',
  'moss-avis.no',
  'nab.no',
  'nationen.no',
  'nettavisen.no',
  'nidaros.no',
  'noblad.no',
  'nordhordland.no',
  'nordlys.no',
  'norsklandbruk.no',
  'nrk.no',
  'oa.no',
  'oblad.no',
  'op.no',
  'ostlendingen.no',
  'oyene.no',
  'pd.no',
  'r-a.no',
  'rablad.no',
  'ranablad.no',
  'ranano.no',
  'rastavanger.no',
  'rb.no',
  'retten.no',
  'rha.no',
  'ringblad.no',
  'ringsaker-blad.no',
  'sa.no',
  'sageneavis.no',
  'sandeavis.no',
  'sandnesposten.no',
  'sb.no',
  'senja247.no',
  'smaalenene.no',
  'sognavis.no',
  'solabladet.no',
  'solungavisa.no',
  'stangeavisa.no',
  'strandbuen.no',
  'sva.no',
  'svelviksposten.no',
  'sydvesten.no',
  'ta.no',
  'tb.no',
  'telen.no',
  'tk.no',
  'totenidag.no',
  'traktor.no',
  'tvedestrandsposten.no',
  'varingen.no',
  'vestbyavis.no',
  'vg.no',
  'vp.no',
];

export interface TitleResult {
  url: string;
  title: string | null;
  description: string | null;
  timestamp: number;
}

export interface FetchTitlesRequest {
  urls: string[];
}

export interface FetchTitlesResponse {
  results: TitleResult[];
}

export type MessageType = 
  | { type: 'FETCH_TITLES'; payload: FetchTitlesRequest }
  | { type: 'FETCH_TITLES_RESULT'; payload: FetchTitlesResponse };

export const CACHE_EXPIRY_MS = 60 * 60 * 1000;
export const FETCH_TIMEOUT_MS = 5000;
